config/routes.rb
GeoNotes::Application.routes.draw do
  root :to => 'pages#home'
  match '/signout', :to => 'sessions#destroy'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  
  resources :notes
  resources :users
  resources :sessions
  resources :tags
end

app/models/note.rb
class Note < ActiveRecord::Base  
  attr_accessor :tag_list
  attr_accessible :content, :longitude, :latitude, :tag_list
  
  validates :content, :presence => true
  validates :user_id, :presence => true
  validates :tag_list, :presence => true
  validates :longitude, :presence => true
  validates :latitude, :presence => true
  belongs_to :user
  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings
  
  before_save :save_tags
  
  def tag_list
    read_attribute(:tag_list) || tags.map(&:name).join(", ")
  end

  def tag_list=(val)
    write_attribute(:tag_list, val)
  end
  
  private
    def save_tags
      self.tags = tag_list.split(/\s*,\s*/).uniq.map do |name|
              Tag.find_or_create_by_name(name)
      end
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  include ApplicationHelper
  before_filter :authenticate
  before_filter :correct_user, :only => [:update, :edit, :destroy]
  def create
    @note = current_user.notes.build(params[:note])
    if @note.save
      flash[:success]="Note created!"
      redirect_to root_path
    else
      render_errors_now(@note)
      gon.note = @note.attributes
      render 'new'
    end
  end
  
  def update
    @note = Note.find(params[:id])
    if @note.update_attributes(params[:note])
      flash[:success]="Note updated!"
      redirect_to root_path
    else
      render_errors_now(@note)
      render 'edit'
    end
  end
  
  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to root_path
  end
  
  def new
    @note = Note.new
    gon.note = nil
    @title = "Create Note"
  end
  
  def show
    @title = "My Note"
    @note = Note.find(params[:id])
    gon.note = @note.attributes
    gon.current_user = current_user.id
  end
  
  def index
    @title = "My Notes"
    @notes = Note.all
      gon.notes=[]
      @notes.each_with_index do |k, index|
        gon.notes[index] = k.attributes
      end    
  end
  
  def edit
    gon.note = @note.attributes
  end
  
  private
    def correct_user
      @note = Note.find(params[:id])
      redirect_to(root_path) unless current_user?(@note.user)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note.html.erb
<div class="hidden", id="note_<%=note.id%>">
	<p><%= note.content %></p>

	<h4><%="#{time_ago_in_words(note.created_at).capitalize} ago by "%> 
	<%= link_to note.user.username, note.user %>
	<% if note.user == current_user %>
	 | <%= link_to "edit", edit_note_path(note) %>
	  <%= button_to "delete", note, :method => :delete,:confirm => "Are you sure" %>
	<% end %>
	</h4>
	<h5>Tags:
	<% note.tags.each do |k| %>
		<%=link_to k.name, k %>
		<%= "·" unless k == note.tags.last %>
	<% end %>
	</h5>
</div>

app/views/notes/_note_form.html.erb
<div id="note-form-wrapper">
	<%= form_for @note do |f| %>
		<h1><%= h1 %></h1>
		<%= render "shared/messages"%>
		<%= f.label "Content" %>
		<%= f.text_area :content %>
		<%= f.label "Tags" %>
		<%= f.text_field :tag_list %>
		<%= f.hidden_field :latitude %>
		<%= f.hidden_field :longitude %>
		<%= f.submit "Submit", :class => "standard_button" %>
	<% end %>
	<% content_for :map_javascript do %>
		<%= javascript_include_tag 'maps/new_note.js' if @note.id.nil? %>
		<%= javascript_include_tag 'maps/edit_note.js' unless @note.id.nil? %>
	<% end %>
</div>

app/views/notes/edit.html.erb
<div id="map"></div>
<div class="hidden">
	<%= render 'notes/note_form', :h1 => "Edit a Note" %>
</div>

app/views/notes/index.html.erb
<%= render 'shared/section_nav' %>

<div id="map"></div>
<% content_for :map_javascript do %>
	<%= javascript_include_tag 'maps/show_note.js' %>
<% end %>

<%= render @notes %>

app/views/notes/new.html.erb
<%= render 'shared/section_nav' %>

<h1>Make a new note!</h1>
<p>Click anywhere on the map to create a new note!</p>
<div id="map"></div>
<div class="hidden"><%= render 'notes/note_form', :h1 => "Create a Note" %></div>

app/views/notes/show.html.erb
<h1>Note by <%=@note.user.username%></h1>
<h5>"<%= @note.content %>"</h5>
<%="Created  #{time_ago_in_words(@note.created_at)} ago."%>
<h5>Tags:</h5>
<% @note.tags.each do |k| %>
	<%= k.name %>
<% end %>
| 
<%= link_to "edit", edit_note_path(@note)%>