config/routes.rb
GeoNotes::Application.routes.draw do
  root :to => 'pages#home'
  match '/signout', :to => 'sessions#destroy'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  
  resources :notes
  resources :users
  resources :sessions
  resources :tags
end

app/views/layouts/_assets.html.erb
<!-- Stylesheets -->
<%= stylesheet_link_tag :all %>
<link rel="stylesheet" href="http://code.leafletjs.com/leaflet-0.3.1/leaflet.css" />
<!--[if lte IE 8]>
    <link rel="stylesheet" href="http://code.leafletjs.com/leaflet-0.3.1/leaflet.ie.css" />
<![endif]-->
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- Javascripts  -->
<%= javascript_include_tag 'jquery.js' %>
<%= javascript_include_tag 'jquery_ujs.js' %>

<%= javascript_include_tag 'application.js' %>

<%= javascript_include_tag 'http://code.leafletjs.com/leaflet-0.3.1/leaflet.js' %>
<%= yield :map_javascript %>

app/views/layouts/_footer.html.erb
<footer>
	<%= link_to "Home", root_path %>
	·
	<%= link_to "About", '/about' %>
	·
	<%= link_to "Contact", '/contact' %>
	
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="title"><h1><%=link_to"GeoNotes", root_path%></h1></div>
	<%= render 'sessions/signin_form'%>
	<% if signed_in? %>	
		<nav>
			<ul>
					<li>
						<%= link_to "Home", root_path%>
					</li>
					<li>
						· <%= link_to "Community", users_path %>
					</li>
			
					<li>
						· <%= link_to "New Note", new_note_path %>
					</li>
					<li>
						· <%= link_to "Tags", tags_path %>
					</li>
					<li>
						· <%= link_to "Edit Account", edit_user_path(current_user) %>
					</li>
					<li>
						· <%= link_to "Sign Out", '/signout' %>
					</li>
			</ul>
		</nav>			
	<% end %>
	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/assets' %>
  <%= include_gon %>

  <%= csrf_meta_tag %>
</head>
<body>
	<%= render 'layouts/header' %>
	
	<section>
		<%= yield %>
	</section>
	<%= render 'layouts/footer'%>
</body>

</html>